TEXT_GAMEOVER  = "YOU RAN OUT OF BALLS.";
TEXT_SCORE     = "YOUR FINAL SCORE IS:\n\n";
TEXT_PAUSE     = "PAUSE";
TEXT_PANEL     = "CONGRATULATIONS! YOU GOT";
TEXT_PANEL_POINT = " POINTS";
STRIKE_TEXT    = "STRIKE!";
SCORE_TEXT     = "PTS: ";
