var CANVAS_WIDTH = 790;
var CANVAS_HEIGHT = 960;

var FONT = "pixel_lcd7regular";
var FONT2 = "SportsJersey-Regular";

var EDGEBOARD_X = 250;
var EDGEBOARD_Y = 0;

var FPS_TIME      = 1000/24;
var DISABLE_SOUND_MOBILE = false;

var STATE_LOADING = 0;
var STATE_MENU    = 1;
var STATE_HELP    = 1;
var STATE_GAME    = 3;

var BATTER_X = (CANVAS_WIDTH/2)-225;
var BATTER_Y = CANVAS_HEIGHT-550;

var PITCHER_X = (CANVAS_WIDTH/2)-105;
var PITCHER_Y = (CANVAS_HEIGHT/2)-433;

var BALL_X = CANVAS_WIDTH/2-50;
var BALL_Y = (CANVAS_HEIGHT/2)-400;

var BALL_TO_THROW;
var STEP_SPEED_BALL_HITTED = 1.3;
var STEP_SPEED_STADIUM;
var AREA_VALUE = new Array();

var OFFSET_FOR_HIT;
var OFFSET_FOR_PERFECT_HIT;
var PERFECT_HIT_X = BALL_X+50;
var PERFECT_HIT_Y = BALL_Y+470;
var ALMOST_MINUS;
var ALMOST_PLUS;
//WHEN BALL IS THROWN
var END_POINT_X = PERFECT_HIT_X;
var END_POINT_Y = CANVAS_HEIGHT;
//WHEN BALL IS HITTED
var END_POINT_X_ALMOST_MINUS_LEFT = (CANVAS_WIDTH/2)-200;
var END_POINT_X_ALMOST_MINUS_RIGHT = (CANVAS_WIDTH/2)+200;
var END_POINT_Y_ALMOST_MINUS = 0;
var END_POINT_X_ALMOST_PLUS_LEFT = (CANVAS_WIDTH/2)-300;
var END_POINT_X_ALMOST_PLUS_RIGHT = (CANVAS_WIDTH/2)+300;
var END_POINT_Y_ALMOST_PLUS = 0;
var END_POINT_X_PERFECT_LEFT = (CANVAS_WIDTH/2)-100;
var END_POINT_X_PERFECT_RIGHT = (CANVAS_WIDTH/2)+100;
var END_POINT_Y_PERFECT = 0;

var START_POINT_STADIUM_X = (CANVAS_WIDTH/2);
var START_POINT_STADIUM_Y = (CANVAS_HEIGHT/2)+250;
var NUM_SPRITE_PLAYERS = 26;
var NUM_SPRITE_BATTING = 18;


var ON_MOUSE_DOWN  = 0;
var ON_MOUSE_UP    = 1;
var ON_MOUSE_OVER  = 2;
var ON_MOUSE_OUT   = 3;
var ON_DRAG_START  = 4;
var ON_DRAG_END    = 5;